const tenders=[
 {id:'A-115081',title:'智慧場館人流分析與營運管理系統建置案',agency:'臺北市政府資訊局',code:'115-IT-092',category:'資訊服務',budget:4800000,deadline:'2026-09-08',date:'2026-09-02',match:96,status:'new'},
 {id:'A-115082',title:'公共空間 AI 影像辨識設備採購案',agency:'桃園市政府工務局',code:'TYCG-115-334',category:'財物採購',budget:2650000,deadline:'2026-09-04',date:'2026-09-02',match:93,status:'urgent'},
 {id:'A-115083',title:'觀光景點旅運數據整合服務委託案',agency:'交通部觀光署',code:'MOTC-115-201',category:'勞務採購',budget:7200000,deadline:'2026-09-16',date:'2026-09-02',match:89,status:'new'},
 {id:'A-115084',title:'智慧停車與車流資訊平台維運案',agency:'新北市政府交通局',code:'NTPC-T-11518',category:'資訊服務',budget:1850000,deadline:'2026-09-05',date:'2026-09-01',match:87,status:'urgent'},
 {id:'A-115085',title:'展館數位導覽與即時人流儀表板建置',agency:'國立科學工藝博物館',code:'NSTM-115-076',category:'勞務採購',budget:2100000,deadline:'2026-09-12',date:'2026-09-01',match:84,status:'open'},
 {id:'A-115086',title:'城市資料治理平台功能擴充案',agency:'高雄市政府資訊中心',code:'KCG-DS-11509',category:'資訊服務',budget:3980000,deadline:'2026-09-18',date:'2026-08-31',match:82,status:'open'},
 {id:'A-115087',title:'運動場館 IoT 環境感測系統採購',agency:'臺中市政府運動局',code:'TCS-115-117',category:'財物採購',budget:1420000,deadline:'2026-09-03',date:'2026-08-31',match:78,status:'urgent'},
 {id:'A-115088',title:'港區數位分身與即時監控可行性研究',agency:'臺灣港務股份有限公司',code:'TIPC-RD-1156',category:'研究服務',budget:860000,deadline:'2026-09-22',date:'2026-08-30',match:76,status:'open'}
];
let rules=JSON.parse(localStorage.getItem('tender-rules')||'null')||[
 {id:1,name:'智慧場館與人流',keywords:['人流','場館','影像辨識'],matches:8,active:true},
 {id:2,name:'IoT 與感測設備',keywords:['IoT','感測器','物聯網'],matches:5,active:true},
 {id:3,name:'資料平台與 AI',keywords:['資料治理','AI','儀表板'],matches:7,active:true},
 {id:4,name:'觀光旅運整合',keywords:['觀光','旅運','地圖'],matches:4,active:true},
 {id:5,name:'智慧停車',keywords:['停車','車流','交通'],matches:3,active:true},
 {id:6,name:'數位分身',keywords:['數位分身','3D','即時監控'],matches:2,active:true}
];
let favorites=new Set(JSON.parse(localStorage.getItem('tender-favorites')||'[]'));
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const money=n=>n>=1000000?`NT$ ${(n/1000000).toFixed(1)}M`:`NT$ ${(n/10000).toFixed(0)}萬`;
const daysLeft=d=>Math.max(0,Math.ceil((new Date(d)-new Date('2026-09-02'))/86400000));
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function tenderRow(t,full=false){const urgent=t.status==='urgent';return `<article class="tender-row" data-id="${t.id}"><span class="agency-badge">${escapeHtml(t.agency.slice(0,2))}</span><div class="tender-main"><h3>${escapeHtml(t.title)}</h3><div class="tender-meta"><span>${escapeHtml(t.agency)}</span><i>·</i><span>${escapeHtml(t.code)}</span><span class="tag ${urgent?'urgent':''}">${urgent?'即將截止':t.status==='new'?'今日新增':escapeHtml(t.category)}</span></div></div>${full?`<div class="tender-side"><b>${money(t.budget)}</b><small>${daysLeft(t.deadline)} 天後截止</small></div><div class="tender-actions"><span class="tag">相符 ${t.match}%</span><button class="star-btn ${favorites.has(t.id)?'saved':''}" data-star="${t.id}" aria-label="收藏">${favorites.has(t.id)?'★':'☆'}</button></div>`:`<div class="tender-side"><b>${money(t.budget)} <button class="star-btn ${favorites.has(t.id)?'saved':''}" data-star="${t.id}" aria-label="收藏">${favorites.has(t.id)?'★':'☆'}</button></b><small>${daysLeft(t.deadline)} 天後截止 · ${t.match}% 相符</small></div>`}</article>`}
function renderDashboard(filter='all'){let data=tenders;if(filter==='new')data=data.filter(x=>x.status==='new');if(filter==='urgent')data=data.filter(x=>x.status==='urgent');$('#dashboardTenderList').innerHTML=data.slice(0,5).map(x=>tenderRow(x)).join('')}
function renderFull(){const q=$('#tenderSearch').value.toLowerCase(),status=$('#statusFilter').value,cat=$('#categoryFilter').value;const data=tenders.filter(t=>(status==='all'||t.status===status)&&(cat==='all'||t.category===cat)&&[t.title,t.agency,t.code].join(' ').toLowerCase().includes(q));$('#fullTenderList').innerHTML=data.length?data.map(x=>tenderRow(x,true)).join(''):'<div class="empty"><b>沒有符合的標案</b>請調整搜尋或篩選條件。</div>'}
function renderFavorites(){const data=tenders.filter(t=>favorites.has(t.id));$('#favoriteList').innerHTML=data.length?data.map(x=>tenderRow(x,true)).join(''):'<div class="empty"><b>尚未收藏標案</b>點選案件右側星號即可加入收藏。</div>'}
function renderRules(){
 $('#miniRuleList').innerHTML=rules.filter(r=>r.active).slice(0,3).map(r=>`<div class="rule-mini"><i></i><div><b>${escapeHtml(r.name)}</b><small>${r.keywords.map(escapeHtml).join(' · ')}</small></div><em>${r.matches}</em></div>`).join('');
 $('#rulesGrid').innerHTML=rules.map(r=>`<article class="panel rule-card"><div class="rule-card-head"><span class="tag">${r.matches} 筆相符</span><label class="switch"><input type="checkbox" data-rule-toggle="${r.id}" ${r.active?'checked':''}><i></i></label></div><h3>${escapeHtml(r.name)}</h3><p>持續監測包含以下關鍵字的政府採購案。</p><div class="rule-keywords">${r.keywords.map(k=>`<span>${escapeHtml(k)}</span>`).join('')}</div><div class="rule-foot"><span>每 6 小時執行</span><button class="text-btn" data-delete-rule="${r.id}">刪除</button></div></article>`).join('');
}
function renderHistory(){const runs=JSON.parse(localStorage.getItem('tender-runs')||'null')||[{time:'2026-09-02 08:30',found:12,duration:'42 秒'},{time:'2026-09-02 02:30',found:3,duration:'39 秒'},{time:'2026-09-01 20:30',found:6,duration:'45 秒'},{time:'2026-09-01 14:30',found:9,duration:'41 秒'}];$('#historyList').innerHTML=runs.map(r=>`<div class="history-item"><i></i><div><b>監測完成 · 新增 ${r.found} 筆標案</b><p>6 個條件已比對，資料同步完成</p></div><time>${r.time}<br>${r.duration}</time></div>`).join('')}
function renderActivity(){$('#activityTimeline').innerHTML=[['找到 12 筆新標案','智慧場館與人流等 4 個條件','10 分前'],['收藏一筆標案','公共空間 AI 影像辨識設備','2 小時'],['寄送每日摘要','摘要已寄至管理員信箱','今天 08:30']].map(a=>`<div class="activity"><i></i><div><b>${a[0]}</b><p>${a[1]}</p></div><time>${a[2]}</time></div>`).join('')}
function showView(name){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageCrumb').textContent=({dashboard:'總覽',tenders:'標案清單',rules:'監測條件',favorites:'我的收藏',history:'執行紀錄',settings:'通知設定'})[name];$('#sidebar').classList.remove('open');if(name==='tenders')renderFull();if(name==='favorites')renderFavorites();if(name==='rules')renderRules();window.scrollTo(0,0)}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function exportCSV(){const rows=[['案號','案名','機關','類別','預算','截止日','相符度'],...tenders.map(t=>[t.code,t.title,t.agency,t.category,t.budget,t.deadline,t.match+'%'])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='標案監測結果_20260902.csv';a.click();URL.revokeObjectURL(a.href);toast('CSV 已匯出')}
function openModal(){$('#ruleModal').hidden=false;$('input[name=name]',$('#ruleForm')).focus()}function closeModal(){$('#ruleModal').hidden=true;$('#ruleForm').reset()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)showView(nav.dataset.view);const jump=e.target.closest('[data-jump]');if(jump)showView(jump.dataset.jump);const star=e.target.closest('[data-star]');if(star){const id=star.dataset.star;favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('tender-favorites',JSON.stringify([...favorites]));renderDashboard($(`#quickFilters .active`)?.dataset.filter||'all');renderFull();renderFavorites();toast(favorites.has(id)?'已加入收藏':'已取消收藏')}const del=e.target.closest('[data-delete-rule]');if(del){rules=rules.filter(r=>r.id!==+del.dataset.deleteRule);localStorage.setItem('tender-rules',JSON.stringify(rules));renderRules();toast('監測條件已刪除')}if(e.target.closest('[data-close]'))closeModal()});
$$('#quickFilters button').forEach(b=>b.addEventListener('click',()=>{$$('#quickFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDashboard(b.dataset.filter)}));
$('#tenderSearch').addEventListener('input',renderFull);$('#statusFilter').addEventListener('change',renderFull);$('#categoryFilter').addEventListener('change',renderFull);
$('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){showView('tenders');$('#tenderSearch').value=e.target.value;renderFull()}});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}if(e.key==='Escape')closeModal()});
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#exportBtn').onclick=exportCSV;$('#exportBtn2').onclick=exportCSV;$('#addRuleBtn').onclick=openModal;$('#addRuleBtn2').onclick=openModal;
$('#ruleForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);rules.unshift({id:Date.now(),name:d.get('name'),keywords:d.get('keywords').split(/[,，]/).map(x=>x.trim()).filter(Boolean),matches:0,active:true});localStorage.setItem('tender-rules',JSON.stringify(rules));renderRules();closeModal();toast('監測條件已建立')});
document.addEventListener('change',e=>{if(e.target.matches('[data-rule-toggle]')){const r=rules.find(x=>x.id===+e.target.dataset.ruleToggle);r.active=e.target.checked;localStorage.setItem('tender-rules',JSON.stringify(rules));renderRules();toast(r.active?'已啟用監測':'已暫停監測')}});
$('#runCrawlerBtn').onclick=()=>{const b=$('#runCrawlerBtn');b.disabled=true;b.innerHTML='<span>↻</span>監測中…';setTimeout(()=>{b.disabled=false;b.innerHTML='<span>↻</span>立即監測';$('#lastRun').textContent='上次更新：剛剛';const runs=JSON.parse(localStorage.getItem('tender-runs')||'[]');runs.unshift({time:'2026-09-02 '+new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'}),found:0,duration:'38 秒'});localStorage.setItem('tender-runs',JSON.stringify(runs.slice(0,10)));renderHistory();toast('監測完成，目前沒有更多新標案')},1600)};
$('.save-settings')?.addEventListener('click',()=>toast('通知設定已儲存'));$('#notificationBtn').onclick=()=>toast('目前有 3 則未讀通知');
const cats=[...new Set(tenders.map(t=>t.category))];$('#categoryFilter').innerHTML+=[...cats].map(c=>`<option>${c}</option>`).join('');renderDashboard();renderFull();renderRules();renderFavorites();renderHistory();renderActivity();
