// Cross-source enhancements: Taiwan Buying + Changi Airport Group (CAG)
// CAG snapshot fields mirror the public Business Opportunities listing.
tenders.forEach(t=>{t.source=t.source||'taiwan';t.currency=t.currency||'TWD';t.region=t.region||'台灣'});
tenders.push(
 {id:'CAG-00563',source:'cag',currency:'SGD',region:'Singapore',title:'Enterprise Grafana licences for Baggage Management System',agency:'Changi Airport Group',code:'2026/00563',category:'IT Cloud Solution',budget:null,deadline:'2026-09-11',date:'2026-09-01',match:94,status:'new',docType:'RFQ'},
 {id:'CAG-00556',source:'cag',currency:'SGD',region:'Singapore',title:'Maintenance and Support Services for Feedback Web Form for Singapore Changi Airport',agency:'Changi Airport Group',code:'2026/00556',category:'IT Consultancy & Professional services',budget:null,deadline:'2026-09-11',date:'2026-08-31',match:91,status:'new',docType:'RFQ'},
 {id:'CAG-00547',source:'cag',currency:'SGD',region:'Singapore',title:'Consolidated Billing for Amazon Web Services (AWS) and Google Cloud Platform (GCP)',agency:'Changi Airport Group',code:'2026/00547',category:'IT Cloud Solution',budget:null,deadline:'2026-09-18',date:'2026-08-28',match:88,status:'open',docType:'Tender'},
 {id:'CAG-00544',source:'cag',currency:'SGD',region:'Singapore',title:'Professional Services for Multi-Robot / Drone Fleet System Integration and Testing Proof-of-Concept',agency:'Changi Airport Group',code:'2026/00544',category:'IT System',budget:null,deadline:'2026-09-10',date:'2026-08-26',match:97,status:'new',docType:'RFQ'},
 {id:'CAG-00534',source:'cag',currency:'SGD',region:'Singapore',title:'Generative Engine Optimisation (GEO) Visibility Audit for the China Market',agency:'Changi Airport Group',code:'2026/00534',category:'Market Research',budget:null,deadline:'2026-09-03',date:'2026-08-26',match:81,status:'urgent',docType:'RFQ'},
 {id:'CAG-00533',source:'cag',currency:'SGD',region:'Singapore',title:'Flight Disembarkation Survey and CCTV Based Baggage Time Motion Study',agency:'Changi Airport Group',code:'2026/00533',category:'Professional Services',budget:null,deadline:'2026-09-02',date:'2026-08-24',match:92,status:'urgent',docType:'RFQ'}
);

rules=rules.map(r=>({sources:['taiwan','cag'],logic:'any',exclude:[],agency:'',category:'all',region:'不限地區',min:'',max:'',dateRange:'30',deadline:'open',notify:true,...r}));
let activeRuleId=null;
const sourceName=t=>t.source==='cag'?'CAG':'台灣採購';
const sourceUrl=t=>t.source==='cag'?'https://sesami.online/cag/businessOpportunities.jsp':'https://www.taiwanbuying.com.tw';
const formatBudget=t=>t.budget?money(t.budget):'未公開預算';

tenderRow=function(t,full=false){const urgent=t.status==='urgent',src=t.source==='cag';return `<article class="tender-row" data-id="${t.id}"><span class="agency-badge">${src?'CAG':escapeHtml(t.agency.slice(0,2))}</span><div class="tender-main"><h3>${escapeHtml(t.title)}</h3><div class="tender-meta"><span class="source-badge ${src?'cag':''}">${sourceName(t)}</span><span>${escapeHtml(t.agency)}</span><i>·</i><span>${escapeHtml(t.code)}</span><span class="tag ${urgent?'urgent':''}">${urgent?'即將截止':t.docType||t.category}</span></div></div>${full?`<div class="tender-side"><b>${formatBudget(t)}</b><small>${daysLeft(t.deadline)} 天後截止</small></div><div class="tender-actions"><span class="tag">相符 ${t.match}%</span><button class="star-btn ${favorites.has(t.id)?'saved':''}" data-star="${t.id}">${favorites.has(t.id)?'★':'☆'}</button><a class="star-btn" href="${sourceUrl(t)}" target="_blank" title="開啟原始資料">↗</a></div>`:`<div class="tender-side"><b>${formatBudget(t)} <button class="star-btn ${favorites.has(t.id)?'saved':''}" data-star="${t.id}">${favorites.has(t.id)?'★':'☆'}</button></b><small>${daysLeft(t.deadline)} 天後截止 · ${t.match}% 相符</small></div>`}</article>`};

function normalizedTerms(value){return Array.isArray(value)?value:value?String(value).split(/[,，]/).map(x=>x.trim()).filter(Boolean):[]}
function ruleMatches(t,r){
 const hay=[t.title,t.agency,t.code,t.category].join(' ').toLowerCase(),keys=normalizedTerms(r.keywords).map(x=>x.toLowerCase()),ex=normalizedTerms(r.exclude).map(x=>x.toLowerCase());
 if(r.sources?.length&&!r.sources.includes(t.source))return false;
 if(keys.length&&(r.logic==='all'?!keys.every(k=>hay.includes(k)):!keys.some(k=>hay.includes(k))))return false;
 if(ex.some(k=>hay.includes(k)))return false;
 if(r.agency&&!t.agency.toLowerCase().includes(r.agency.toLowerCase()))return false;
 if(r.category&&r.category!=='all'&&!t.category.toLowerCase().includes(r.category.toLowerCase()))return false;
 if(r.region&&r.region!=='不限地區'&&r.region!=='全台灣'&&t.region!==r.region)return false;
 if(t.budget&&r.min&&t.budget<Number(r.min)*10000)return false;if(t.budget&&r.max&&t.budget>Number(r.max)*10000)return false;
 if(r.deadline==='7'&&daysLeft(t.deadline)>7)return false;if(r.deadline==='30'&&daysLeft(t.deadline)>30)return false;
 return true;
}
function activeRule(){return rules.find(r=>r.id===activeRuleId)}
function renderSavedRules(){const box=$('#savedRulePills');if(!box)return;box.innerHTML=rules.filter(r=>r.active).map(r=>`<button data-apply-rule="${r.id}" class="${r.id===activeRuleId?'active':''}">${escapeHtml(r.name)} · ${tenders.filter(t=>ruleMatches(t,r)).length}</button>`).join('')}
renderFull=function(){const q=$('#tenderSearch').value.toLowerCase(),status=$('#statusFilter').value,cat=$('#categoryFilter').value,src=$('#sourceFilter')?.value||'all',rule=activeRule();const data=tenders.filter(t=>(src==='all'||t.source===src)&&(status==='all'||t.status===status)&&(cat==='all'||t.category===cat)&&(!rule||ruleMatches(t,rule))&&[t.title,t.agency,t.code,t.category].join(' ').toLowerCase().includes(q));$('#fullTenderList').innerHTML=data.length?data.map(x=>tenderRow(x,true)).join(''):'<div class="empty"><b>沒有符合的標案</b>試著移除部分條件或改用「任一關鍵字」。</div>';const tokens=[];if(src!=='all')tokens.push(src==='cag'?'來源：CAG':'來源：台灣採購');if(status!=='all')tokens.push(`狀態：${status==='new'?'今日新增':'即將截止'}`);if(cat!=='all')tokens.push(`類別：${cat}`);if(rule)tokens.push(`搜尋條件：${rule.name}`);$('#activeFilters').innerHTML=tokens.map(x=>`<span class="filter-token">${escapeHtml(x)}</span>`).join('');renderSavedRules()};
renderDashboard=function(filter='all'){let data=tenders;if(filter==='new')data=data.filter(x=>x.status==='new');if(filter==='urgent')data=data.filter(x=>x.status==='urgent');$('#dashboardTenderList').innerHTML=data.slice(0,6).map(x=>tenderRow(x)).join('')};
renderFavorites=function(){const data=tenders.filter(t=>favorites.has(t.id));$('#favoriteList').innerHTML=data.length?data.map(x=>tenderRow(x,true)).join(''):'<div class="empty"><b>尚未收藏標案</b>點選案件右側星號即可加入收藏。</div>'};
renderRules=function(){
 $('#miniRuleList').innerHTML=rules.filter(r=>r.active).slice(0,3).map(r=>`<div class="rule-mini"><i></i><div><b>${escapeHtml(r.name)}</b><small>${normalizedTerms(r.keywords).map(escapeHtml).join(' · ')}</small></div><em>${tenders.filter(t=>ruleMatches(t,r)).length}</em></div>`).join('');
 $('#rulesGrid').innerHTML=rules.map(r=>`<article class="panel rule-card"><div class="rule-card-head"><span class="tag">${tenders.filter(t=>ruleMatches(t,r)).length} 筆相符</span><div class="rule-card-actions"><button data-edit-rule="${r.id}" title="修改">✎</button><button data-copy-rule="${r.id}" title="複製">⧉</button><label class="switch"><input type="checkbox" data-rule-toggle="${r.id}" ${r.active?'checked':''}><i></i></label></div></div><div class="rule-sources">${(r.sources||[]).map(s=>`<span class="${s==='cag'?'cag':''}">${s==='cag'?'CAG':'TW'}</span>`).join('')}</div><h3>${escapeHtml(r.name)}</h3><p>${r.logic==='all'?'全部符合':'任一符合'} · ${r.deadline==='open'?'尚未截止':r.deadline+' 天內截止'}</p><div class="rule-keywords">${normalizedTerms(r.keywords).map(k=>`<span>${escapeHtml(k)}</span>`).join('')}</div><div class="rule-foot"><span>${r.notify?'每日摘要通知':'不通知'}</span><button class="text-btn" data-delete-rule="${r.id}">刪除</button></div></article>`).join('');renderSavedRules();
};
function fillRuleForm(r={}){const f=$('#ruleForm');f.reset();f.elements.id.value=r.id||'';f.elements.name.value=r.name||'';f.elements.keywords.value=normalizedTerms(r.keywords).join(', ');f.elements.exclude.value=normalizedTerms(r.exclude).join(', ');f.elements.agency.value=r.agency||'';f.elements.category.value=r.category||'all';f.elements.region.value=r.region||'不限地區';f.elements.min.value=r.min||'';f.elements.max.value=r.max||'';f.elements.dateRange.value=r.dateRange||'30';f.elements.deadline.value=r.deadline||'open';f.elements.notify.checked=r.notify!==false;$$('[name=sources]',f).forEach(x=>x.checked=(r.sources||['taiwan','cag']).includes(x.value));const logic=f.querySelector(`[name=logic][value="${r.logic||'any'}"]`);if(logic)logic.checked=true;$('#ruleModalTitle').textContent=r.id?'修改搜尋條件':'建立搜尋條件';$('#ruleSubmitBtn').textContent=r.id?'儲存修改':'儲存並開始監測';updatePreview()}
function updatePreview(){const f=$('#ruleForm'),data=new FormData(f);const draft={sources:data.getAll('sources'),keywords:data.get('keywords'),exclude:data.get('exclude'),logic:data.get('logic'),agency:data.get('agency'),category:data.get('category'),region:data.get('region'),min:data.get('min'),max:data.get('max'),deadline:data.get('deadline')};const n=tenders.filter(t=>ruleMatches(t,draft)).length;$('#matchPreview').textContent=n;const src=draft.sources.length===2?'全部來源':draft.sources[0]==='cag'?'CAG':'台灣採購';$('#ruleSummary').textContent=`${src} · ${draft.logic==='all'?'全部':'任一'}關鍵字 · ${draft.deadline==='open'?'尚未截止':draft.deadline+' 天內截止'}`}
$('#ruleForm').addEventListener('input',updatePreview);$('#sourceFilter').addEventListener('change',renderFull);
document.addEventListener('click',e=>{const apply=e.target.closest('[data-apply-rule]');if(apply){activeRuleId=+apply.dataset.applyRule;renderFull()}const edit=e.target.closest('[data-edit-rule]');if(edit){fillRuleForm(rules.find(r=>r.id===+edit.dataset.editRule));$('#ruleModal').hidden=false}const copy=e.target.closest('[data-copy-rule]');if(copy){const r=rules.find(x=>x.id===+copy.dataset.copyRule);rules.unshift({...r,id:Date.now(),name:r.name+'（副本）'});localStorage.setItem('tender-rules',JSON.stringify(rules));renderRules();toast('搜尋條件已複製')}const tmpl=e.target.closest('[data-template]');if(tmpl){const presets={it:{name:'資訊系統與雲端服務',keywords:'系統, cloud, software, IT System',category:'all'},iot:{name:'IoT 與智慧設備',keywords:'IoT, 感測, sensor, monitoring',category:'all'},marketing:{name:'活動與行銷服務',keywords:'活動, 行銷, event, marketing',category:'all'}};fillRuleForm(presets[tmpl.dataset.template]);$('#ruleModal').hidden=false}});
$('#clearRuleFilter').onclick=()=>{activeRuleId=null;renderFull()};$('#advancedFilterBtn').onclick=()=>{fillRuleForm(activeRule()||{});$('#ruleModal').hidden=false};
$('#syncSourcesBtn').onclick=async()=>{const b=$('#syncSourcesBtn');b.disabled=true;b.textContent='↻ 同步中…';try{const res=await fetch('/api/sync/cag',{cache:'no-store'});if(!res.ok)throw new Error('sync failed');const data=await res.json();if(!data.ok)throw new Error(data.error||'sync failed');for(let i=tenders.length-1;i>=0;i--)if(tenders[i].source==='cag')tenders.splice(i,1);data.items.forEach((t,i)=>tenders.push({...t,match:Math.max(72,96-(i%7)*3),status:daysLeft(t.deadline)<=3?'urgent':t.date==='2026-09-02'?'new':'open'}));$('#cagCount').textContent=data.count;$('#lastRun').textContent='上次更新：剛剛';renderDashboard();renderFull();renderRules();toast(`CAG 已同步 ${data.count} 筆，台灣採購條件同步完成`)}catch(err){toast('目前為靜態預覽；啟動 server.py 後可進行 CAG 即時同步')}finally{b.disabled=false;b.textContent='↻ 同步全部'}};

// Replace the original form action with edit-aware persistence.
const originalForm=$('#ruleForm'),cleanForm=originalForm.cloneNode(true);originalForm.replaceWith(cleanForm);
cleanForm.addEventListener('input',updatePreview);
cleanForm.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(cleanForm),id=Number(d.get('id'))||Date.now(),rule={id,name:d.get('name'),keywords:normalizedTerms(d.get('keywords')),exclude:normalizedTerms(d.get('exclude')),sources:d.getAll('sources'),logic:d.get('logic'),agency:d.get('agency'),category:d.get('category'),region:d.get('region'),min:d.get('min'),max:d.get('max'),dateRange:d.get('dateRange'),deadline:d.get('deadline'),notify:d.get('notify')==='on',matches:0,active:true};const idx=rules.findIndex(r=>r.id===id);idx>=0?rules.splice(idx,1,rule):rules.unshift(rule);localStorage.setItem('tender-rules',JSON.stringify(rules));renderRules();$('#ruleModal').hidden=true;toast(idx>=0?'搜尋條件已更新':'搜尋條件已建立')});

const originalOpen=openModal;openModal=function(){fillRuleForm({});$('#ruleModal').hidden=false;$('[name=name]',$('#ruleForm')).focus()};
$('#addRuleBtn').onclick=openModal;$('#addRuleBtn2').onclick=openModal;
const enhancedCats=[...new Set(tenders.map(t=>t.category))];$('#categoryFilter').innerHTML='<option value="all">全部類別</option>'+enhancedCats.map(c=>`<option>${c}</option>`).join('');
renderDashboard();renderFull();renderRules();renderFavorites();
