(()=>{
 const items=[["replicator","Sales","商機開發","Replicator","找到值得追蹤的下一個機會。","監測標案、篩選商機，整理提案前的需求。","01"],["markets","Solutions","產品與方案","Markets","從需求出發，找到合適的方案。","探索合作夥伴產品，比較規格與應用組合。","02"],["designer","Workbench","方案設計","Designer","讓需求成為可以討論的提案。","配置方案、整理元件，製作提案與報價內容。","03"],["financial","Management","營運管理","Financial","掌握每個專案的收入與支出。","整理報價、收支與客戶資料，追蹤營運進度。","04"],["dashboard","Workbench","使用情境","Dashboard","讓使用情境有清楚的呈現。","探索人員與資產追蹤，梳理操作介面與指標。","05"],["rtls","Applications","智慧空間","Digital Twin + RTLS","從空間資訊，走向應用設計。","探索定位、數位分身與智慧空間應用。","06"],["esg","Applications","永續應用","ESG Report","讓應用成果留下可追蹤的紀錄。","探索防護、稽核與永續報告的應用情境。","07"]];const current="replicator";
 const local=/^(127\.0\.0\.1|localhost)$/.test(location.hostname)&&/^873[1-7]$/.test(location.port);
 const home=local?'http://127.0.0.1:8720/':'https://labubutaiwan.netlify.app/';
 const url=id=>local?'http://127.0.0.1:'+({"dashboard":8731,"designer":8732,"esg":8733,"financial":8734,"markets":8735,"replicator":8736,"rtls":8737})[id]+'/':'https://toolkit-'+id+'.netlify.app/';
 const mount=()=>{if(document.querySelector('ms-toolkit-shell'))return;document.body.dataset.msTool=current;
 const host=document.createElement('ms-toolkit-shell');document.body.append(host);const sh=host.attachShadow({mode:'open'});
 sh.innerHTML=`<style>:host{position:fixed;right:18px;bottom:18px;z-index:9000;font:14px/1.5 "MiSans",sans-serif;color:#252c36}*{box-sizing:border-box}button,a{font:inherit}button{cursor:pointer}a{color:inherit;text-decoration:none}button:focus-visible,a:focus-visible{outline:3px solid #758ca8;outline-offset:3px}.trigger{border:1px solid #ffffff35;background:#252c36;color:white;box-shadow:0 5px 22px #252c3625;padding:10px 16px 10px 10px;border-radius:14px;display:flex;align-items:center;gap:8px}.trigger svg{width:27px;height:27px}.trigger span{font-size:11px;color:#b9c6d7;display:block;text-align:left}.trigger b{font-size:12px;letter-spacing:.04em}.panel{position:absolute;right:0;bottom:68px;width:340px;max-width:calc(100vw - 32px);max-height:calc(100dvh - 190px);overflow:auto;background:#fafbf9;border:1px solid #dadddf;border-radius:18px;box-shadow:0 18px 60px #252c3633;padding:18px}.panel[hidden]{display:none}.head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.head b{letter-spacing:.12em;font-size:11px}.close{border:0;background:#e8eeea;border-radius:50%;width:30px;height:30px}.home{display:block;background:#252c36;color:white;padding:12px;border-radius:9px;margin-bottom:10px}.row{display:flex;justify-content:space-between;align-items:center;padding:9px 10px;border-radius:9px}.row:hover{background:#e8ecf0}.row[aria-current]{background:#e0e5eb}.row small{display:block;color:#616872;font-size:11px}.row b{font-size:13px}.note{font-size:11px;color:#616872;margin:12px 2px 0}@media(max-width:600px){:host{right:12px;bottom:12px}.trigger{padding:9px}.trigger .label{display:none}.panel{bottom:58px}}@media print{:host{display:none}}.company-logo{width:106px;height:auto;object-fit:contain;background:white;border-radius:4px;padding:3px 5px}.head b{display:flex;align-items:center;gap:8px}.head .company-logo{width:126px}.trigger{gap:10px}@media(max-width:600px){.trigger .company-logo{width:92px}} .email-contact{border-top:1px solid #dadddf;margin-top:12px;padding-top:12px;display:flex;flex-direction:column;gap:8px}.email-contact b{font-size:11px;color:#616872}.email-contact a{font-size:12px;color:#465a70;text-decoration:underline;text-underline-offset:3px} :host-context(html[data-ms-theme="dark"]) .panel{background:#222832;color:#e2eee8;border-color:#414956}:host-context(html[data-ms-theme="dark"]) .row:hover,:host-context(html[data-ms-theme="dark"]) .row[aria-current]{background:#28473f}:host-context(html[data-ms-theme="dark"]) .row small,:host-context(html[data-ms-theme="dark"]) .note{color:#b2c7bd}:host-context(html[data-ms-theme="dark"]) .email-contact a{color:#b1bbc8}/* reading-v2 */.row{padding:12px 10px;min-height:48px}.row b{font-size:15px}.row small,.note,.email-contact b{font-size:13px;line-height:1.65}.email-contact a{font-size:14px;line-height:1.7}.close{width:40px;height:40px}.trigger b{font-size:14px}</style>
 <section class="panel" id="tools" aria-label="工作平台導覽" hidden><div class="head"><b><img class="company-logo" src="/brand/motospatial.png" alt="Motospatial" width="423" height="102"> / TOOLKIT</b><button class="close" aria-label="關閉工具選單">×</button></div><a class="home" href="${home}" target="_blank" rel="noopener">← 返回公司官網</a><nav aria-label="工具切換">${items.map(t=>`<a class="row" href="${url(t[0])}" target="_blank" rel="noopener" ${t[0]===current?'aria-current="page"':''}><div><b>${t[3]}</b><small>${t[1]} · ${t[2]}</small></div><span>${t[0]===current?'目前':'↗'}</span></a>`).join('')}</nav><div class="email-contact"><b>聯絡 Motospatial</b><a href="/contact.html" target="_blank" rel="noopener">填寫洽詢 ↗</a><a href="mailto:contact@motospatial.com">contact@motospatial.com</a></div><p class="note">郵件連結會開啟郵件程式，由你確認後寄出。工具以新分頁開啟。</p></section>
 <button class="trigger" aria-expanded="false" aria-controls="tools" aria-label="開啟 Motospatial 工具選單"><img class="company-logo" src="/brand/motospatial.png" alt="Motospatial" width="423" height="102"><div class="label"><b>${items.find(t=>t[0]===current)?.[3]||'Toolkit'}　⌃</b></div></button>`;
 const trigger=sh.querySelector('.trigger'),panel=sh.querySelector('.panel');
 const close=()=>{panel.hidden=true;trigger.setAttribute('aria-expanded','false');trigger.focus()};
 trigger.onclick=()=>{panel.hidden=!panel.hidden;trigger.setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)sh.querySelector('.home').focus()};
 sh.querySelector('.close').onclick=close;sh.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
 document.addEventListener('pointerdown',e=>{if(!panel.hidden&&!e.composedPath().includes(host)){panel.hidden=true;trigger.setAttribute('aria-expanded','false')}});
 };if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();